version: '3'
services:
    jenkins:
        image: jenkins/jenkins:2.332.2-lts-jdk11
        build:
            context: .
        ports:
            - 8080:8080
            - 50000:50000
        container_name: jenkins 
        volumes:
            - ${PWD}/jenkins_home:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock
        user:
            root
        networks:
            - net
networks:
    net: 
